### ISSUE TITLE
[proposal] 所定の接頭詞か接尾詞がついていた場合はタイムラインチャンネルに発言を転送しない

### ISSUE THREAD

**Issue by loxygenK** [watano1168/limitimes#11]
サーバ全体に発言が公開されるのが気になる場合などに，所定の接頭詞か接尾詞がついていた場合にタイムラインに転送しないようにする機能がほしいなあと思いました．

### 詳細
`~` や `^` などの 1 文字記号を判定に用いようと考えています．
例えば `^` の場合は…
```
^進捗出ません
```
```
^進捗出ません^
```
```
進捗出ません^
```
これらは全てタイムラインに転送されないようになります．

### 考えられる悪影響

- **治安が最悪になる可能性があります**．
  発言内容がクローズドになるので，変なことが水面下で蔓延る可能性が否定できません．

ご検討よろしくお願いします :pray:

**Comment by 2RiniaR** [comment]
良い機能だと思います。
オンラインゲーム等により、個人的には接頭辞として `!` に馴染みがあるため、`!` もしくは `!\n` が先頭に付くメッセージをタイムラインに転送しないようにしたいと思います。

**Comment by loxygenK** [comment]
なるほど，ありがとうございます :pray:
もし実装する場合は自分が手つけてみたいなあと思っているんですが問題ないでしょうか?

それと，治安が最悪になるかもしれない問題はわたのさん的にはどうお考えかお聞かせいただけるとうれしいです． (個人的に author の意向を聞いておきたいと考えています)

**Comment by 2RiniaR** [comment]
問題ないです！ぜひPRをください！
治安の問題に関しては今に始まったことじゃないので、考えるだけ無駄だと思います。綺麗な花というのは、黒ずんだ泥沼に幾度汚されたとしても、その色彩を魅せるから素敵なものなんです。

**Comment by loxygenK** [comment]
わかりました，ありがとうございます! 来週中には PR を出せるようにしようと思います．
